# source directory
src : ../wikiart/
# destination directory
dst : ../test/
# Number of images to generate
n_cameras : 10
# Number of lights added to the scene
n_lights : [2,5] 
# Number of occlusions added to the scene
n_objects: [1,4]
# render only ambient images, free of shadows and lighting effects
ambient: False
# Adding perspective distortions with corresponding homographies
homography: True
# visibility of occlusions
visible: True