# source directory
src : ../wikiart/
# destination directory
dst : ../SIDAR-Lights/
# Number of images to generate
n_cameras : 50
# Number of lights added to the scene
n_lights : [2,5] 
# Number of occlusions added to the scene
n_objects: [1,4]
# render ambient images, free of shadows and lighting effects
ambient: false
# Adding perspective distortions with corresponding homographies
homography: false
# visibility of occlusions
visible: false